### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by mtcp290** [b23r0/Heroinn#3]
I use windows 10 to compile and it doesn't work on windows 2012.
Can you add socks proxy?

**Comment by b23r0** [comment]
Hope to give more detailed error message.

Also, the range supported by Heroinn
Win10+(Windows Server 2019+) & Linux & BSD & OSX

Windows 2012 may be supported in the future. This is mainly influenced by the interactive Pty Shell functionality.

**Comment by b23r0** [comment]
Socks5 will be supported in the future, how long it will take to see if I have enough time to maintain the project. 

Maybe you can extend my working hours with a tip. : )
