### ISSUE TITLE
Issue with 'shell' 

### ISSUE THREAD

**Issue by Teach2Breach** [b23r0/Heroinn#6]
I plan to dig into this more but don't have a ton of time right now. When right-clicking a target and selecting shell, get the following error:
![image](https://user-images.githubusercontent.com/105792760/192896192-67119bab-d326-4f56-980f-b16e0ec5a016.png)
This is on Windows 10 for both server and client.

**Comment by Teach2Breach** [comment]
Also, I saw your comment about socks proxy and getting a tip. You should add a wallet address so we can tip. I would be happy to do so if the project continues to be supported (and especially if you add a socks proxy).

**Comment by Teach2Breach** [comment]
Actually it appears that the source code for heroinn_shell.exe is missing. I see the binary in the target/debug folder, but where is the source?

**Comment by Teach2Breach** [comment]
sketchy

**Comment by b23r0** [comment]
`heroinn_shell.exe` in here https://github.com/b23r0/Heroinn/tree/master/target/debug，

source code : https://github.com/b23r0/alacritty-driver

**Comment by b23r0** [comment]
You need to put heroinn_shell in the same directory to make sure it can be started normally.

**Comment by b23r0** [comment]
> sketchy

haha，if you are willing to contribute or donate, he will become better

**Comment by Teach2Breach** [comment]
I am willing to do that, I just was concerned when I saw a binary with no source code. Could easily be used to infect heroinn user systems (not just their targets). Has been done before :) . If this alacritty-driver is the source used for heroinn-shell.exe, then I'll build from source and try that. I really like this framework, if I can get the shell working, and it looks good, I'll put together some PRs to add features. Thanks for the response.

**Comment by Teach2Breach** [comment]
Works well! I really like it... I should add, I am testing against very popular EDR and no issues with preventions. :)
![image](https://user-images.githubusercontent.com/105792760/193831514-33b791a1-97a8-4641-9135-0de38cd89729.png)

**Comment by b23r0** [comment]
Development has been temporarily suspended due to my recent vacation. When I come back from vacation, I'll resume development work. If you're interested in getting involved in development, I'll still be reviewing and merging your code while on vacation. Would love to see your support.

**Comment by peterpavles** [comment]
> Works well! I really like it... I should add, I am testing against very popular EDR and no issues with preventions. :) ![image](https://user-images.githubusercontent.com/105792760/193831514-33b791a1-97a8-4641-9135-0de38cd89729.png)

could you state the the step you used to make client and server run
i compiled from sources using cargo build, then i generated payload successfully, started the listener but i run client it does not connect and client exits stating [ERROR] parse master connection info faild
