### ISSUE TITLE
Module shell

### ISSUE THREAD

**Issue by saensmompere** [b23r0/Heroinn#8]
Hi, how I can build? I'm have error:
error[E0583]: file not found for module `Shell`
 --> heroinn_client/src/module/mod.rs:2:1
  |
2 | pub mod Shell;
  | ^^^^^^^^^^^^^^
  |
  = help: to create the module `Shell`, create file "heroinn_client/src/module/Shell.rs" or "heroinn_client/src/module/Shell/mod.rs"

error[E0432]: unresolved import `module::Shell::ShellClient`
  --> heroinn_client/src/main.rs:23:5

**Comment by crispud** [comment]
I solved moving the file heroinn_client/src/module/shell.rs into heroinn_client/src/module/Shell.rs
